### ISSUE TITLE
Draft review

### ISSUE THREAD

**Issue by josemotanet** [vis-kid/octopress_drafts_previewer#1]
Hey Ed! I'm pitching in with issues so a record can be kept and code/content can be shared in between.

So here's a couple of things I've noticed so far:
1. Too many bolds are being used and they loose value. Also, they become distracting. I realize you're trying to bring attention to a couple of words but they are really not necessary. Besides, there's the associated risk of them reading the bold words and not reading anything else.
2. There are some punctuation remarks I'll submit a PR about; minor things.
3. First post: In the Functions Overview chapter, I think you might want to rephrase those questions into something more declarative. You want to keep your content as classy as possible. My suggestion would be to avoid _marketing-y_, flashy content strategies. Stick to writing quality, valuable content.

For now that's it. I'll be sending a PR soon. Cheers!

**Comment by vis-kid** [comment]
Hey!

Very good points! Thanks for taking the time!!
Totally agree on the non-marketing speak. Not interested in that approach at all. Valuable content with substance is definitely what I’m aiming for :)

Will go over it again tonight.

Thanks!
